spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oscboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r


  # ??? SQL ?? ??
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # hibernate ??
    database : mysql
    hibernate.ddl-auto : update
    hibernate.naming.strategy : org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl : false
    properties.hibernate.format_sql : true
    properties.hibernate.enable_lazy_load_no_trans : true
